SELECT
    P.PRODUCT_ID,
    CASE
        WHEN COALESCE(SUM(U.UNITS), 0) = 0 THEN 0
        ELSE ROUND(
            COALESCE(SUM(P.PRICE * U.UNITS), 0) :: NUMERIC / SUM(U.UNITS),
            2
        )
    END AS AVERAGE_PRICE
FROM
    PRICES P
    LEFT JOIN UNITSSOLD U ON P.PRODUCT_ID = U.PRODUCT_ID
    AND U.PURCHASE_DATE BETWEEN P.START_DATE
    AND P.END_DATE
GROUP BY
    P.PRODUCT_ID;